/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'inverse-on-surface': '#2b313c',
        'surface-variant': '#2f3540',
        'on-primary-fixed': '#002022',
        'on-secondary-fixed': '#00201c',
        'primary-fixed': '#74f5ff',
        'on-primary-container': '#006a71',
        'surface-container': '#1a202a',
        secondary: '#59dbc7',
        'tertiary-fixed-dim': '#40deb3',
        'on-tertiary-container': '#006d55',
        'on-surface-variant': '#b9cacb',
        error: '#ffb4ab',
        'secondary-fixed': '#79f7e3',
        tertiary: '#dcfff0',
        'on-background': '#dde2f1',
        'surface-tint': '#00dbe7',
        'surface-card': '#161E2D',
        'tertiary-fixed': '#65fbcf',
        'surface-container-high': '#242a35',
        'on-primary': '#00363a',
        'on-primary-fixed-variant': '#004f54',
        'on-error': '#690005',
        'secondary-fixed-dim': '#59dbc7',
        'status-running': '#00FF41',
        outline: '#849495',
        'status-fault': '#FF3131',
        background: '#0e141e',
        'on-tertiary': '#00382a',
        'status-warning': '#F59E0B',
        'outline-variant': '#3a494b',
        'on-surface': '#dde2f1',
        'on-tertiary-fixed-variant': '#00513e',
        'surface-bright': '#333945',
        'surface-container-lowest': '#080e18',
        'chart-teal': '#00A896',
        surface: '#0e141e',
        'error-container': '#93000a',
        'tertiary-container': '#5bf3c7',
        'primary-fixed-dim': '#00dbe7',
        'on-secondary-container': '#00332c',
        'on-error-container': '#ffdad6',
        'surface-container-low': '#161c26',
        'inverse-primary': '#00696f',
        'surface-container-highest': '#2f3540',
        primary: '#e1fdff',
        'primary-container': '#00f2ff',
        'inverse-surface': '#dde2f1',
        'chart-blue': '#3B82F6',
        'status-stopped': '#94A3B8',
        'on-secondary': '#003731',
        'surface-dim': '#0e141e',
        'chart-cyan': '#00F2FF',
        'secondary-container': '#00a694',
        'on-tertiary-fixed': '#002117',
        'on-secondary-fixed-variant': '#005047',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'breakpoint-desktop': '1440px',
        'internal-padding': '20px',
        'grid-columns': '12',
        'container-padding': '24px',
        'widget-gap': '16px',
        'breakpoint-tablet': '1024px',
      },
      fontFamily: {
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'data-display': ['JetBrains Mono', 'monospace'],
        'display-lg': ['Hanken Grotesk', 'sans-serif'],
        'label-sm': ['JetBrains Mono', 'monospace'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'body-md': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-lg': ['38px', { lineHeight: '48px', fontWeight: '600' }],
        'data-display': ['32px', { lineHeight: '38px', fontWeight: '700' }],
        'display-lg': ['56px', { lineHeight: '64px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'label-sm': ['14px', { lineHeight: '20px', fontWeight: '500' }],
        'headline-md': ['28px', { lineHeight: '38px', fontWeight: '600' }],
        'body-lg': ['22px', { lineHeight: '32px', fontWeight: '400' }],
      },
    },
  },
  plugins: [],
};
